### ISSUE TITLE
Time track buttons not working

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/premise-time-tracker#3]
I managed to install the plugin.

Unfortunately, when editing a Time track, the buttons are not working (START, STOP & + Add new buttons).

After checking the Console, no errors were shown.

Could this be due to the same `get_rest_url()` we commented out earlier today?

**Comment by francoisjacquet** [comment]
@mvallejo3  I have had a look at the **Start** button code:

The PremiseField does not implement any `onclick` event.
The `core.js` file does not relate any event to the `ptt_start` id.
The code inspector does not mention any event tied to the button either:
![screenshot from 2016-02-19 16 45 03](https://cloud.githubusercontent.com/assets/4723501/13189947/6173dd52-d728-11e5-8598-baa27cfaad22.png)

Apart from that, the issue has been reproduced on Firefox, Chrome, and on 2 different Wordpress install, with or without additional plugins.

**Comment by mvallejo3** [comment]
@francoisjacquet were you able to make this work? I cannot reproduce the issue.
